spin_manifest_version = 2

[application]
name = "benwis-leptos"
version = "0.1.0"
authors = ["benwis <ben@celcyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "benwis-leptos"

[component.benwis-leptos]
source = "target/wasm32-wasi/release/benwis_leptos.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
sqlite_databases = ["default"]

[component.benwis-leptos.build]
command = "LEPTOS_BIN_TARGET_TRIPLE=wasm32-wasi cargo leptos build --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "ui"

[component.ui]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site", destination = "/" }]
