spin_manifest_version = 2

[application]
name = "benwis-leptos"
version = "0.1.0"
authors = ["benwis <ben@celcyon.com>"]
description = ""

[[trigger.http]]
route = "/favicon.ico"
component = "favicon"

[component.favicon]
source = "wasi/spin-fileserver/spin_static_fs.wasm"
files = [{ source = "target/site/favicon.ico", destination = "/favicon.ico" }]
#files = ["target/site/favicon.ico"]
#environment = { FILE_ROOT = "/target/site" }

[[trigger.http]]
route = "/..."
component = "benwis-leptos"

[component.benwis-leptos]
source = "target/wasm32-wasi/release/benwis_leptos.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
sqlite_databases = ["default"]

[component.benwis-leptos.build]
command = "LEPTOS_BIN_TARGET_TRIPLE=wasm32-wasi cargo leptos build --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "ui"

[component.ui]
#source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
source = "wasi/spin-fileserver/spin_static_fs.wasm"
files = [{ source = "target/site/pkg", destination = "/" }]


[[trigger.http]]
route = "/fonts/..."
component = "fonts"

[component.fonts]
#source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
source = "wasi/spin-fileserver/spin_static_fs.wasm"
files = [{ source = "target/site/fonts", destination = "/" }]


[[trigger.http]]
route = "/img/..."
component = "images"

[component.images]
#source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
source = "wasi/spin-fileserver/spin_static_fs.wasm"
files = [{ source = "target/site/img", destination = "/" }]

[[trigger.http]]
route = "/components/..."
component = "components"

[component.components]
#source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
source = "wasi/spin-fileserver/spin_static_fs.wasm"
files = [{ source = "public/components", destination = "/" }]


